- hosts: web-server
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true
    - name: Ensure Apache is started
      systemd:
        name: apache2
        state: started
        enabled: true

- hosts: database-server
  become: true
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
        update_cache: true
    - name: Ensure MySQL is started
      systemd:
        name: mysql
        state: started
        enabled: true

- hosts: load-balancer
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: true
    - name: Ensure HAProxy is started
      systemd:
        name: haproxy
        state: started
        enabled: true
